### ISSUE TITLE
[my_hidden_doors] Supposedly locked doors, are not.

### ISSUE THREAD

**Issue by debagos** [minetest-mods/mydoors#29]
The hidden doors have "Locked" in their descriptions, besides not being locked:

https://github.com/minetest-mods/mydoors/blob/a12f72ead03e734abab483614a86aa386669ea1c/my_hidden_doors/init.lua#L15-L18
and
https://github.com/minetest-mods/mydoors/blob/a12f72ead03e734abab483614a86aa386669ea1c/my_hidden_doors/init.lua#L30-L34

**Comment by SmallJoker** [comment]
8307238
